name: history_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
  rxdart: ^0.26.0
  hydrated_bloc: ^7.0.0-nullsafety.2
  path_provider: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  cached_network_image: ^3.0.0
#  political_cartoon_repository:
#    git:
#      url: https://github.com/DoubleTrio/political_cartoon_repository.git
#      ref: main
  political_cartoon_repository:
    path: ../../repository/political_cartoon_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0
  network_image_mock: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/placeholder.png
    - assets/images/unit5/
    - assets/images/unit6/

  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SFNSDisplay-Regular.otf
        - asset: assets/fonts/SFNSDisplay-Light.otf
        - asset: assets/fonts/SFNSDisplay-Bold.otf
        - asset: assets/fonts/SFNSText-RegularItalic.otf