name: hawktoons
description: An open-sourced educational history app to learn about political cartoons and images
version: 1.1.1+3
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  equatable: ^2.0.0
  rxdart: ^0.26.0
  hydrated_bloc: ^7.0.0-nullsafety.2
  path_provider: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  cached_network_image: ^3.0.0
  flow_builder: ^0.0.2
  shimmer: ^2.0.0
  flutter_spinkit: ^5.0.0
  political_cartoon_repository:
    git:
      url: https://github.com/DoubleTrio/political_cartoon_repository.git
      ref: main
  image_repository:
    path: packages/image_repository/
#  political_cartoon_repository:
#    path: ../../repository/political_cartoon_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0
  network_image_mock: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: launcher_icon
  image_path: assets/images/app/app_icon2.png

flutter_native_splash:
  color_dark: "#2B2B2B"
  color: '#FFFFFF'
  image: assets/images/app/app_icon2.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/app/

  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SanFrancisco/SFNSDisplay-Regular.otf
        - asset: assets/fonts/SanFrancisco/SFNSDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SFNSDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/SanFrancisco/SFNSText-RegularItalic.otf
          style: italic